# Конфигурация BlueMapPlayerControl
# Сообщения плагина

messages:
  # Сообщения для игрока о своей видимости
  self:
    now-visible: "Теперь вы §b§lвидимы§r на карте"
    now-invisible: "Теперь вы §6§lневидимы§r на карте"
    no-permission: "§cУ вас нет прав для изменения своей видимости на карте"
  
  # Сообщения для управления видимостью других игроков
  others:
    now-visible: "%player% теперь §b§lвидим§r на карте"
    now-invisible: "%player% теперь §6§lневидим§r на карте"
    no-permission: "§cУ вас нет прав для изменения видимости других игроков"
    player-not-found: "§eИгрок \"%player%\" не найден"
  
  # Общие сообщения
  general:
    must-be-player: "§cТолько игроки могут скрывать себя на карте"
  
  # Сообщения для команды перезагрузки
  reload:
    success: "§aКонфигурация BlueMapPlayerControl перезагружена!"
    no-permission: "§cУ вас нет прав для перезагрузки конфигурации!" 